### ISSUE TITLE
[bug] Restart container losing installed license

### ISSUE THREAD

**Issue by liangrog** [sonatype/docker-nexus-iq-server#35]
Hi there,
I encountered an issue with the current iq server docker image 1.77.0 version.

When I restart the container, it will prompt me to install the license again which I have done previously. The image is using persistence storage. Everything else seems to be fine with storing in /sonatyp-work/data. 

[config]
---
sonatypeWork: "/sonatype-work"
server:
  applicationConnectors:
  - type: http
    port: 8070
  adminConnectors:
  - type: http
    port: 8071
  requestLog:
    appenders:
    - type: file
      currentLogFilename: "/var/log/nexus-iq-server/request.log"
      archivedLogFilenamePattern: "/var/log/nexus-iq-server/request-%d.log.gz"
      archivedFileCount: 5
logging:
  level: DEBUG
  loggers:
    com.sonatype.insight.scan: INFO
    eu.medsea.mimeutil.MimeUtil2: INFO
    org.apache.http: INFO
    org.apache.http.wire: ERROR
    org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader: WARN
    org.eclipse.jetty: INFO
    org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter: INFO
  appenders:
  - type: console
    threshold: INFO
    logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger
      - %msg%n"
  - type: file
    threshold: ALL
    currentLogFilename: "/var/log/nexus-iq-server/clm-server.log"
    archivedLogFilenamePattern: "/var/log/nexus-iq-server/clm-server-%d.log.gz"
    logFormat: "%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger
      - %msg%n"
    archivedFileCount: 5
createSampleData: true

[Log]

Starting Nexus IQ Server instance ID d1064831-8208-4c30-b027-6addf4455163 on hostname sonatype-nexus-iq-sonatype-nexus-iq-server-6df444dfdf-mk8b9 (IP address 10.61.69.17).
03:59:00.017 [main] INFO com.sonatype.insight.brain.service.InsightBrainService - Starting Nexus IQ Server instance ID d1064831-8208-4c30-b027-6addf4455163 on hostname sonatype-nexus-iq-sonatype-nexus-iq-server-6df444dfdf-mk8b9 (IP address 10.61.69.17).
2019-11-12 03:59:01,550+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - |------------------------------------------
2019-11-12 03:59:01,550+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - |
2019-11-12 03:59:01,550+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - | Initializing Nexus IQ Server 1 release 77.0-01
2019-11-12 03:59:01,551+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - |
2019-11-12 03:59:01,551+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - |------------------------------------------
2019-11-12 03:59:01,551+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - Configuration file: /etc/nexus-iq-server/config.yml
2019-11-12 03:59:01,639+0000 INFO [main] *SYSTEM io.dropwizard.server.DefaultServerFactory - Registering jersey handler with root path prefix: /
2019-11-12 03:59:01,640+0000 INFO [main] *SYSTEM io.dropwizard.server.DefaultServerFactory - Registering admin handler with root path prefix: /
2019-11-12 03:59:01,641+0000 INFO [main] *SYSTEM io.dropwizard.assets.AssetsBundle - Registering AssetBundle with name: assets for path /assets/*
2019-11-12 03:59:01,660+0000 INFO [main] *SYSTEM io.dropwizard.assets.AssetsBundle - Registering AssetBundle with name: policyAssets for path /policy-assets/*
Started Nexus IQ Server instance ID d1064831-8208-4c30-b027-6addf4455163 on hostname sonatype-nexus-iq-sonatype-nexus-iq-server-6df444dfdf-mk8b9 (IP address 10.61.69.17).
2019-11-12 03:59:01,660+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - Started Nexus IQ Server instance ID d1064831-8208-4c30-b027-6addf4455163 on hostname sonatype-nexus-iq-sonatype-nexus-iq-server-6df444dfdf-mk8b9 (IP address 10.61.69.17).
2019-11-12 03:59:01,661+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.DatabaseConfigProvider - Using embedded database at /sonatype-work/data
2019-11-12 03:59:01,662+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.OperationalDataStoreProvider - Initializing the insight_brain_ods data store.
2019-11-12 03:59:01,958+0000 INFO [main] *SYSTEM com.sonatype.insight.db.DatabaseSchemaPopulator - Ignoring request to populate database schema insight_brain_ods because it already exists.
2019-11-12 03:59:01,975+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatabaseMigrator - Current version of database insight_brain_ods: 147
2019-11-12 03:59:02,769+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.OperationalDataStoreProvider - Initialized the insight_brain_ods data store in 1107 ms.
2019-11-12 03:59:02,770+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.DatabaseConfigProvider - Using embedded database at /sonatype-work/data
2019-11-12 03:59:02,771+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatamartProvider - Initializing the insight_brain_dm data store.
2019-11-12 03:59:02,825+0000 INFO [main] *SYSTEM com.sonatype.insight.db.DatabaseSchemaPopulator - Ignoring request to populate database schema insight_brain_dm because it already exists.
2019-11-12 03:59:02,831+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatabaseMigrator - Current version of database insight_brain_dm: 8
2019-11-12 03:59:02,842+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatamartProvider - Initialized the insight_brain_dm data store in 71 ms.
2019-11-12 03:59:02,842+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.DatabaseConfigProvider - Using embedded database at /sonatype-work/data
2019-11-12 03:59:02,843+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.ThirdPartyScansProvider - Initializing the insight_brain_third_party_scans data store.
2019-11-12 03:59:02,893+0000 INFO [main] *SYSTEM com.sonatype.insight.db.DatabaseSchemaPopulator - Ignoring request to populate database schema insight_brain_third_party_scans because it already exists.
2019-11-12 03:59:02,900+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatabaseMigrator - Current version of database insight_brain_third_party_scans: 5
2019-11-12 03:59:02,912+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.ThirdPartyScansProvider - Initialized the insight_brain_third_party_scans data store in 69 ms.
2019-11-12 03:59:02,912+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.DatabaseConfigProvider - Using embedded database at /sonatype-work/data
2019-11-12 03:59:02,913+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.AggregationDataStoreProvider - Initializing the insight_brain_aggregation data store.
2019-11-12 03:59:02,963+0000 INFO [main] *SYSTEM com.sonatype.insight.db.DatabaseSchemaPopulator - Ignoring request to populate database schema insight_brain_aggregation because it already exists.
2019-11-12 03:59:02,982+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.DatabaseMigrator - Current version of database insight_brain_aggregation: 11
2019-11-12 03:59:03,004+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.db.AggregationDataStoreProvider - Initialized the insight_brain_aggregation data store in 91 ms.
2019-11-12 03:59:08,592+0000 INFO [main] *SYSTEM com.sonatype.insight.brain.service.InsightBrainService - Server base URL: null
2019-11-12 03:59:09,570+0000 INFO [main] *SYSTEM java.util.prefs - Created user preferences directory.
2019-11-12 03:59:09,579+0000 INFO [main] *SYSTEM **com.sonatype.insight.brain.product.license.CLMLicenseManager - No license installed
org.sonatype.licensing.LicensingException: Unable to verify license: There is no license certificate installed for 'CLM'.**
        at org.sonatype.licensing.trial.internal.DefaultTrialLicenseManager.verifyLicense(Unknown Source)
        at org.sonatype.licensing.product.internal.DefaultProductLicenseManager.getLicenseDetails(Unknown Source)
        at com.sonatype.insight.brain.product.license.CLMLicenseManager.loadLicense(CLMLicenseManager.java:124)
        at com.sonatype.insight.brain.service.ApplicationLifecycle.boot(ApplicationLifecycle.java:67)
        at com.sonatype.insight.brain.service.InsightBrainService.run(InsightBrainService.java:209)
        at com.sonatype.insight.brain.service.InsightBrainService.run(InsightBrainService.java:74)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at com.sonatype.insight.brain.service.InsightBrainService$2.run(InsightBrainService.java:154)
        at com.sonatype.insight.brain.service.InsightBrainService$2.run(InsightBrainService.java:136)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at com.sonatype.insight.brain.service.InsightBrainService.run(InsightBrainService.java:176)
        at com.sonatype.insight.brain.service.InsightBrainService.main(InsightBrainService.java:104)
Caused by: de.schlichtherle.license.NoLicenseInstalledException: CLM
        at codeguard.licensing.zts.itm(Unknown Source)
        at codeguard.licensing.tpg.omj(Unknown Source)
        at codeguard.licensing.tpg.itm(Unknown Source)
        at codeguard.licensing.bab.mif(Unknown Source)
        ... 13 common frames omitted

**Comment by collinpeters** [comment]
@liangrog can I ask how you initially created the container and how you are starting/restarting it?

I have tried it with and without a custom volume and it worked for me both ways:
**With**
1. `docker volume create --name sonatype-work`
1. `docker run -d -p 8070:8070 -p 8071:8071 --name nexus-iq-server -v sonatype-work:/sonatype-work sonatype/nexus-iq-server`
1. Login at http://localhost:8070, directed to license install, install the license and land at getting starting page
1. `docker restart nexus-iq-server`
1. Login at http://localhost:8070 and land at getting started page

**Without**
1. `docker run -d -p 8070:8070 -p 8071:8071 --name nexus-iq-server sonatype/nexus-iq-server`
1. Login at http://localhost:8070, directed to license install, install the license and land at getting starting page
1. `docker volume ls` shows new volume automatically created
1. `docker restart nexus-iq-server`
1. Login at http://localhost:8070 and land at getting started page

**Comment by liangrog** [comment]
@collinpeters Thanks for investigating it. Sorry I forgot to mention a few details:
I run it in Kubernetes using deployment, EBS as persistence volume. Then I use kubectl delete pod command to delete the pod. When it comes backup, it loses the license. 

A guy from Sonatype suggested I should persist the license and set the path in config.yaml of which I have yet to try out.

**Comment by collinpeters** [comment]
That sounds right - see https://github.com/sonatype/docker-nexus-iq-server#runtime-server-configuration for those details

**Comment by liangrog** [comment]
All the data already persist as per instruction. I am a bit surprised that the license isn't stored in the bake-in database or saved to the disk.

**Comment by collinpeters** [comment]
Is the `JAVA_OPTS` environment variable being overridden? If its possible to enter the container you could verify some values. For example with the defaults above I do `docker exec -it nexus-iq-server /bin/bash` to enter the container and then
```
bash-4.4$ echo $JAVA_OPTS 
-Djava.util.prefs.userRoot=/sonatype-work/javaprefs
bash-4.4$ echo $SONATYPE_WORK/
/sonatype-work/
bash-4.4$ head -c200 /sonatype-work/javaprefs/.java/.userPrefs/com/sonatype/clm/prefs.xml 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="license" value="cylwwtYx6FhG0TNwDV6oOk5
```
This shows the license being stored in the java prefs. Then it should be a matter of verifying that the folder is being persisted. And if you can't find it in the default spot, then that might indicate why it isn't surviving restarts. [This link](https://stackoverflow.com/a/1320798/354767) shows where the defaults for prefs, though the more important point is what `JAVA_OPTS` is or if it is being overridden somewhere.

**Comment by liangrog** [comment]
@collinpeters Thanks for the tip. I have found the culprit. As per [docker hub instruction](https://hub.docker.com/r/sonatype/nexus-iq-server):

> There is an environment variable JAVA_OPTS that is being used to pass JVM arguments to the java command that launches IQ server. The default value is -Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs.

I was passing the default value into the container. However the container took the `${SONATYPE_WORK}` literally.  So I ended up having the JAVA_OPTS set as
/opt/sonatype/nexus-iq-server/${SONATYPE_WORK}/javaprefs

All fixed now. Thank you.
